# Generated by Django 4.2.4 on 2023-10-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Subject',
            field=models.TextField(max_length=300),
        ),
    ]
